# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sistema_pb2 as sistema__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sistema_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServidorParesStub:
    """============================================================================
    SERVIÇO 1: Servidor de Pares (Chave, Valor)
    ============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insercao = channel.unary_unary(
                '/sistema_distribuido.ServidorPares/Insercao',
                request_serializer=sistema__pb2.InsercaoRequest.SerializeToString,
                response_deserializer=sistema__pb2.InsercaoResponse.FromString,
                _registered_method=True)
        self.Consulta = channel.unary_unary(
                '/sistema_distribuido.ServidorPares/Consulta',
                request_serializer=sistema__pb2.ConsultaRequest.SerializeToString,
                response_deserializer=sistema__pb2.ConsultaResponse.FromString,
                _registered_method=True)
        self.Activacao = channel.unary_unary(
                '/sistema_distribuido.ServidorPares/Activacao',
                request_serializer=sistema__pb2.ActivacaoRequest.SerializeToString,
                response_deserializer=sistema__pb2.ActivacaoResponse.FromString,
                _registered_method=True)
        self.Termino = channel.unary_unary(
                '/sistema_distribuido.ServidorPares/Termino',
                request_serializer=sistema__pb2.TerminoParesRequest.SerializeToString,
                response_deserializer=sistema__pb2.TerminoParesResponse.FromString,
                _registered_method=True)


class ServidorParesServicer:
    """============================================================================
    SERVIÇO 1: Servidor de Pares (Chave, Valor)
    ============================================================================
    """

    def Insercao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consulta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Activacao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Termino(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServidorParesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insercao': grpc.unary_unary_rpc_method_handler(
                    servicer.Insercao,
                    request_deserializer=sistema__pb2.InsercaoRequest.FromString,
                    response_serializer=sistema__pb2.InsercaoResponse.SerializeToString,
            ),
            'Consulta': grpc.unary_unary_rpc_method_handler(
                    servicer.Consulta,
                    request_deserializer=sistema__pb2.ConsultaRequest.FromString,
                    response_serializer=sistema__pb2.ConsultaResponse.SerializeToString,
            ),
            'Activacao': grpc.unary_unary_rpc_method_handler(
                    servicer.Activacao,
                    request_deserializer=sistema__pb2.ActivacaoRequest.FromString,
                    response_serializer=sistema__pb2.ActivacaoResponse.SerializeToString,
            ),
            'Termino': grpc.unary_unary_rpc_method_handler(
                    servicer.Termino,
                    request_deserializer=sistema__pb2.TerminoParesRequest.FromString,
                    response_serializer=sistema__pb2.TerminoParesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sistema_distribuido.ServidorPares', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sistema_distribuido.ServidorPares', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServidorPares:
    """============================================================================
    SERVIÇO 1: Servidor de Pares (Chave, Valor)
    ============================================================================
    """

    @staticmethod
    def Insercao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sistema_distribuido.ServidorPares/Insercao',
            sistema__pb2.InsercaoRequest.SerializeToString,
            sistema__pb2.InsercaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consulta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sistema_distribuido.ServidorPares/Consulta',
            sistema__pb2.ConsultaRequest.SerializeToString,
            sistema__pb2.ConsultaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Activacao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sistema_distribuido.ServidorPares/Activacao',
            sistema__pb2.ActivacaoRequest.SerializeToString,
            sistema__pb2.ActivacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Termino(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sistema_distribuido.ServidorPares/Termino',
            sistema__pb2.TerminoParesRequest.SerializeToString,
            sistema__pb2.TerminoParesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServidorCentralStub:
    """============================================================================
    SERVIÇO 2: Servidor Centralizador (Estilo Napster)
    ============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Registro = channel.unary_unary(
                '/sistema_distribuido.ServidorCentral/Registro',
                request_serializer=sistema__pb2.RegistroRequest.SerializeToString,
                response_deserializer=sistema__pb2.RegistroResponse.FromString,
                _registered_method=True)
        self.Mapeamento = channel.unary_unary(
                '/sistema_distribuido.ServidorCentral/Mapeamento',
                request_serializer=sistema__pb2.MapeamentoRequest.SerializeToString,
                response_deserializer=sistema__pb2.MapeamentoResponse.FromString,
                _registered_method=True)
        self.Termino = channel.unary_unary(
                '/sistema_distribuido.ServidorCentral/Termino',
                request_serializer=sistema__pb2.TerminoCentralRequest.SerializeToString,
                response_deserializer=sistema__pb2.TerminoCentralResponse.FromString,
                _registered_method=True)


class ServidorCentralServicer:
    """============================================================================
    SERVIÇO 2: Servidor Centralizador (Estilo Napster)
    ============================================================================
    """

    def Registro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mapeamento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Termino(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServidorCentralServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Registro': grpc.unary_unary_rpc_method_handler(
                    servicer.Registro,
                    request_deserializer=sistema__pb2.RegistroRequest.FromString,
                    response_serializer=sistema__pb2.RegistroResponse.SerializeToString,
            ),
            'Mapeamento': grpc.unary_unary_rpc_method_handler(
                    servicer.Mapeamento,
                    request_deserializer=sistema__pb2.MapeamentoRequest.FromString,
                    response_serializer=sistema__pb2.MapeamentoResponse.SerializeToString,
            ),
            'Termino': grpc.unary_unary_rpc_method_handler(
                    servicer.Termino,
                    request_deserializer=sistema__pb2.TerminoCentralRequest.FromString,
                    response_serializer=sistema__pb2.TerminoCentralResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sistema_distribuido.ServidorCentral', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sistema_distribuido.ServidorCentral', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServidorCentral:
    """============================================================================
    SERVIÇO 2: Servidor Centralizador (Estilo Napster)
    ============================================================================
    """

    @staticmethod
    def Registro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sistema_distribuido.ServidorCentral/Registro',
            sistema__pb2.RegistroRequest.SerializeToString,
            sistema__pb2.RegistroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mapeamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sistema_distribuido.ServidorCentral/Mapeamento',
            sistema__pb2.MapeamentoRequest.SerializeToString,
            sistema__pb2.MapeamentoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Termino(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sistema_distribuido.ServidorCentral/Termino',
            sistema__pb2.TerminoCentralRequest.SerializeToString,
            sistema__pb2.TerminoCentralResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
