# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sistema.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sistema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsistema.proto\x12\x13sistema_distribuido\"/\n\x0fInsercaoRequest\x12\r\n\x05\x63have\x18\x01 \x01(\x05\x12\r\n\x05valor\x18\x02 \x01(\t\"\"\n\x10InsercaoResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\" \n\x0f\x43onsultaRequest\x12\r\n\x05\x63have\x18\x01 \x01(\x05\"!\n\x10\x43onsultaResponse\x12\r\n\x05valor\x18\x01 \x01(\t\"1\n\x10\x41\x63tivacaoRequest\x12\x1d\n\x15identificador_servico\x18\x01 \x01(\t\"#\n\x11\x41\x63tivacaoResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x15\n\x13TerminoParesRequest\"0\n\x14TerminoParesResponse\x12\x18\n\x10\x63haves_definidas\x18\x01 \x01(\x05\"@\n\x0fRegistroRequest\x12\x1d\n\x15identificador_servico\x18\x01 \x01(\t\x12\x0e\n\x06\x63haves\x18\x02 \x03(\x05\".\n\x10RegistroResponse\x12\x1a\n\x12\x63haves_processadas\x18\x01 \x01(\x05\"\"\n\x11MapeamentoRequest\x12\r\n\x05\x63have\x18\x01 \x01(\x05\"3\n\x12MapeamentoResponse\x12\x1d\n\x15identificador_servico\x18\x01 \x01(\t\"\x17\n\x15TerminoCentralRequest\"4\n\x16TerminoCentralResponse\x12\x1a\n\x12\x63haves_registradas\x18\x01 \x01(\x05\x32\xfd\x02\n\rServidorPares\x12W\n\x08Insercao\x12$.sistema_distribuido.InsercaoRequest\x1a%.sistema_distribuido.InsercaoResponse\x12W\n\x08\x43onsulta\x12$.sistema_distribuido.ConsultaRequest\x1a%.sistema_distribuido.ConsultaResponse\x12Z\n\tActivacao\x12%.sistema_distribuido.ActivacaoRequest\x1a&.sistema_distribuido.ActivacaoResponse\x12^\n\x07Termino\x12(.sistema_distribuido.TerminoParesRequest\x1a).sistema_distribuido.TerminoParesResponse2\xad\x02\n\x0fServidorCentral\x12W\n\x08Registro\x12$.sistema_distribuido.RegistroRequest\x1a%.sistema_distribuido.RegistroResponse\x12]\n\nMapeamento\x12&.sistema_distribuido.MapeamentoRequest\x1a\'.sistema_distribuido.MapeamentoResponse\x12\x62\n\x07Termino\x12*.sistema_distribuido.TerminoCentralRequest\x1a+.sistema_distribuido.TerminoCentralResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sistema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSERCAOREQUEST']._serialized_start=38
  _globals['_INSERCAOREQUEST']._serialized_end=85
  _globals['_INSERCAORESPONSE']._serialized_start=87
  _globals['_INSERCAORESPONSE']._serialized_end=121
  _globals['_CONSULTAREQUEST']._serialized_start=123
  _globals['_CONSULTAREQUEST']._serialized_end=155
  _globals['_CONSULTARESPONSE']._serialized_start=157
  _globals['_CONSULTARESPONSE']._serialized_end=190
  _globals['_ACTIVACAOREQUEST']._serialized_start=192
  _globals['_ACTIVACAOREQUEST']._serialized_end=241
  _globals['_ACTIVACAORESPONSE']._serialized_start=243
  _globals['_ACTIVACAORESPONSE']._serialized_end=278
  _globals['_TERMINOPARESREQUEST']._serialized_start=280
  _globals['_TERMINOPARESREQUEST']._serialized_end=301
  _globals['_TERMINOPARESRESPONSE']._serialized_start=303
  _globals['_TERMINOPARESRESPONSE']._serialized_end=351
  _globals['_REGISTROREQUEST']._serialized_start=353
  _globals['_REGISTROREQUEST']._serialized_end=417
  _globals['_REGISTRORESPONSE']._serialized_start=419
  _globals['_REGISTRORESPONSE']._serialized_end=465
  _globals['_MAPEAMENTOREQUEST']._serialized_start=467
  _globals['_MAPEAMENTOREQUEST']._serialized_end=501
  _globals['_MAPEAMENTORESPONSE']._serialized_start=503
  _globals['_MAPEAMENTORESPONSE']._serialized_end=554
  _globals['_TERMINOCENTRALREQUEST']._serialized_start=556
  _globals['_TERMINOCENTRALREQUEST']._serialized_end=579
  _globals['_TERMINOCENTRALRESPONSE']._serialized_start=581
  _globals['_TERMINOCENTRALRESPONSE']._serialized_end=633
  _globals['_SERVIDORPARES']._serialized_start=636
  _globals['_SERVIDORPARES']._serialized_end=1017
  _globals['_SERVIDORCENTRAL']._serialized_start=1020
  _globals['_SERVIDORCENTRAL']._serialized_end=1321
# @@protoc_insertion_point(module_scope)
